esp32:
  board: m5stack-core2
  framework:
    type: arduino

psram:
  mode: quad
  speed: 80MHz

external_components:
  - source: github://martydingo/esphome-axp192
    components: [axp192]

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23

i2c:
  - id: bus_a
    sda: GPIO21
    scl: GPIO22
    scan: true

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 24

# powers the display/backlight rails and exposes the battery level
sensor:
  - platform: axp192
    id: axp192_id
    model: M5CORE2
    address: 0x34
    i2c_id: bus_a
    update_interval: 30s
    battery_level:
      name: "${friendly_name} Battery Level"

display:
  - platform: mipi_spi
    id: core2_display
    model: M5CORE2
    lambda: |-
      it.print(10, 10, id(roboto), "Loading...");

touchscreen:
  - platform: ft63x6
    id: core2_touchscreen
    interrupt_pin: GPIO39

time:
  - platform: bm8563
    update_interval: never
  - platform: homeassistant
    on_time_sync:
      then:
        bm8563.write_time:
